import fs from 'fs';
import path from 'path';

// Read the built HTML from Vite's dist folder
const htmlPath = path.join(process.cwd(), 'dist', 'index.html');
if (!fs.existsSync(htmlPath)) {
  console.error('Error: dist/index.html not found. Please run "vite build" first.');
  process.exit(1);
}

let html = fs.readFileSync(htmlPath, 'utf-8');

// Inline JS and CSS files referenced in the HTML
const distPath = path.join(process.cwd(), 'dist');
const assetPath = path.join(distPath, 'assets');

// Find and inline script files
html = html.replace(/<script type="module" src="([^"]+)"><\/script>/g, (match, src) => {
  const scriptPath = path.join(distPath, src);
  if (fs.existsSync(scriptPath)) {
    const scriptContent = fs.readFileSync(scriptPath, 'utf-8');
    return `<script type="module">${scriptContent}</script>`;
  }
  return match;
});

// Find and inline CSS files
html = html.replace(/<link rel="stylesheet" href="([^"]+)">/g, (match, href) => {
  const cssPath = path.join(distPath, href);
  if (fs.existsSync(cssPath)) {
    const cssContent = fs.readFileSync(cssPath, 'utf-8');
    return `<style>${cssContent}</style>`;
  }
  return match;
});

// Escape for template literal
const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');
const output = `// Auto-generated: HTML content embedded at build time
// This file is generated by build-html.js after Vite build
export const indexHTML = \`${escaped}\`;`;
fs.writeFileSync('src/html-content.js', output);
console.log('HTML content embedded successfully with inlined assets');
