import fs from 'fs';
import path from 'path';

console.log('=== 開始構建 HTML 內容 ===');

// Read the built HTML from Vite's dist folder
const htmlPath = path.join(process.cwd(), 'dist', 'index.html');
if (!fs.existsSync(htmlPath)) {
  console.error('❌ 錯誤: dist/index.html 不存在。請先執行 "npm run build" 或 "vite build"');
  process.exit(1);
}

console.log('✓ 找到 dist/index.html');

let html = fs.readFileSync(htmlPath, 'utf-8');
console.log('✓ 讀取 HTML 檔案');

// Inline JS and CSS files referenced in the HTML
const distPath = path.join(process.cwd(), 'dist');
const assetPath = path.join(distPath, 'assets');

// Find and inline script files (support both relative and absolute paths)
let scriptCount = 0;
html = html.replace(/<script[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi, (match, src) => {
  scriptCount++;
  // Handle both relative paths and absolute paths starting with /
  // Remove leading slash if present and handle relative paths
  let scriptPath = src.startsWith('/') 
    ? path.join(distPath, src.substring(1)) 
    : path.join(distPath, src);
  
  // Normalize path
  scriptPath = path.normalize(scriptPath);
  
  if (fs.existsSync(scriptPath)) {
    try {
      const scriptContent = fs.readFileSync(scriptPath, 'utf-8');
      console.log(`✓ 內聯腳本: ${src}`);
      // Extract any attributes from the original script tag
      const attributes = match.match(/<script([^>]*)>/i)?.[1] || '';
      // Remove src attribute and keep others
      const otherAttrs = attributes.replace(/src=["'][^"']+["']/gi, '').trim();
      return `<script${otherAttrs ? ' ' + otherAttrs : ''}>${scriptContent}</script>`;
    } catch (error) {
      console.warn(`⚠️  警告: 無法內聯腳本 ${src}:`, error.message);
      return match;
    }
  } else {
    console.warn(`⚠️  警告: 腳本檔案不存在: ${scriptPath} (來源: ${src})`);
    return match;
  }
});

if (scriptCount === 0) {
  console.warn('⚠️  警告: 沒有找到任何需要內聯的腳本標籤');
}

// Find and inline CSS files (support both link tags and @import)
let cssCount = 0;
html = html.replace(/<link[^>]*rel=["']stylesheet["'][^>]*href=["']([^"']+)["'][^>]*>/gi, (match, href) => {
  cssCount++;
  // Handle both relative paths and absolute paths starting with /
  let cssPath = href.startsWith('/') 
    ? path.join(distPath, href.substring(1)) 
    : path.join(distPath, href);
  
  // Normalize path
  cssPath = path.normalize(cssPath);
  
  if (fs.existsSync(cssPath)) {
    try {
      const cssContent = fs.readFileSync(cssPath, 'utf-8');
      console.log(`✓ 內聯樣式: ${href}`);
      return `<style>${cssContent}</style>`;
    } catch (error) {
      console.warn(`⚠️  警告: 無法內聯 CSS ${href}:`, error.message);
      return match;
    }
  } else {
    console.warn(`⚠️  警告: CSS 檔案不存在: ${cssPath} (來源: ${href})`);
    return match;
  }
});

if (cssCount === 0) {
  console.warn('⚠️  警告: 沒有找到任何需要內聯的樣式標籤');
}

// Also handle preload links for CSS/JS that might be referenced
html = html.replace(/<link[^>]*rel=["'](modulepreload|preload)["'][^>]*href=["']([^"']+)["'][^>]*>/gi, (match, rel, href) => {
  // Remove preload links as we're inlining everything
  return '';
});

// Escape for template literal
const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');
const output = `// Auto-generated: HTML content embedded at build time
// This file is generated by build-html.js after Vite build
// DO NOT EDIT THIS FILE MANUALLY
export const indexHTML = \`${escaped}\`;`;
fs.writeFileSync('src/html-content.js', output);

console.log('');
console.log('=== 構建完成 ===');
console.log(`✓ 內聯了 ${scriptCount} 個腳本檔案`);
console.log(`✓ 內聯了 ${cssCount} 個樣式檔案`);
console.log('✓ HTML 內容已嵌入到 src/html-content.js');
console.log('');
